name: Playwright Pytest Automation

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      GMAIL_TO: 'aruna.kumari72@gmail.com'
      url: ${{ secrets.APP_URL }}
      Email: ${{ secrets.USERNAME }}
      Password: ${{ secrets.PWD }}
      APPPassword: ${{ secrets.APP_PWD }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Create .env file for local variables
      - name: Create .env file
        run: |
          echo "APP_URL=${{ env.url }}" >> .env
          echo "USERNAME=${{ env.Email }}" >> .env
          echo "PWD=${{ env.Password }}" >> .env
          echo "APP_PWD=${{ env.APPPassword }}" >> .env

      # Step 5: Run Playwright tests
      - name: Run Pytest with Allure
        run: |
          pytest --alluredir=allure-results

      # Step 6: Generate Allure Report
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      # Step 7: Upload Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
<<<<<<< HEAD
          name: allure-report
          path: allure-report
=======
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
          allow_empty_commit: true

      

      # Step 10: Send Allure Report Link via Gmail
      - name: Send Allure Report Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{  secrets.USERNAME }}
          password: ${{ secrets.APP_PWD }}
          subject: "Quickbase Automation Test Report"
          to: ${{ env.GMAIL_TO }}
          from: ${{ secrets.USERNAME }}
          html_body: |
            Hello,<br><br>
            The latest Quickbase web automation Allure report is available at:<br>
            <a href="https://aruna-gowda.github.io/quickBase/">View Allure Report</a><br><br>
            Regards,<br>
            Aruna
>>>>>>> cfb8e68b705d2c61f8cd3d2fdc106b75286a8572
